### PR TITLE
Update de_DE.lang - 25.01.15

### PR DESCRIPTION
**Pull request by iTimmyLP**

### CODE REVIEW

**Comment by AfterLifeLochie** [comment]
This is no longer valid because I've started to rewrite the root language file.

Could you please port this to the new language version (see en_US.lang)?

**Comment by iTimmyLP** [comment]
I have port the nee one.
#Close

**Comment by iTimmyLP** [comment]
Can you send me the Build that you use in your test envioment? I want test that is every fine from the translation

**Comment by CaitlynMainer** [comment]
We don't use a "build" for testing, check the source out, and load it up in Eclipse/Idea there are a ton of tutorials on the Forge forums.  No builds will be preformed on the dev branch ATM because someone would ignore the warnings of everything is broken and then complain that it broke everything.

**Pull request closed without merging**
