### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by Timmy94W**
now is everything up-to.date:
Added the Obelisks,
Fixed: localization entries.

### CODE REVIEW

**Comment by AfterLifeLochie** [comment]
Did you happen to miss `item.jacksonNotebook.name` - it was previously suffixed with Notizbuch, but now it's just Notebook - is this right?

**Comment by Timmy94W** [comment]
Yes. I have changed it, after i saw the model from it. my first thought was, that you mean a boot to write in and not a electronic device

**Comment by AfterLifeLochie** [comment]
No, it'll be a help manual - but it'll be formatted like a notebook would (think, say, kladde; rough draft-like).

**Comment by Timmy94W** [comment]
Ah ok. For me it looks like a mobile computer. Should i change it complete?

**Comment by AfterLifeLochie** [comment]
I'm cool with either way - my German is pretty rusty - but imagine it being formatted as an "in the field notebook". "kladde" is the first word which comes to mind, but you're the native speaker here. :)

**Comment by Timmy94W** [comment]
In my opinion is both ok. in the early series he writes in his notebook ( made of paper ) later he used a electronic notebook if my memory do not let me down

**Comment by AfterLifeLochie** [comment]
That is true - though I felt like most of his notes on the Stargate would be on paper because of their age

**Comment by Timmy94W** [comment]
Ah ok. So "Notizbuch" ist the better choice

**Pull request closed without merging**
